### PR TITLE
Update fingerprints.yml

### PR DESCRIPTION
**Pull request by 7destiny**
Added 1 gang switch, and like _TZ3000_fvh3pjaz, there is a problem that the light turns off after 2 minutes, so please fix it.

### CODE REVIEW

**Comment by Mariano-Github** [comment]
Hi,
Please try with the code in folder zigbee-switch-v6.5-test

If works well i will merge

**Comment by 7destiny** [comment]
I don't know how to install and test it.

**Comment by 7destiny** [comment]
I tested it with Creating Drivers for Zigbee Devices with difficulty. It works fine. Please merge.

**Comment by 7destiny** [comment]
So far it works fine. please merge

**Comment by Mariano-Github** [comment]
Ok, Thanks

I will be the publish de new version driver in the channel.
I have a bit busy

**Comment by Mariano-Github** [comment]
Hi,

The zigbee-switch-Mc-v6.5 has the changes
The driver version published in the channel has the changes too

I will delete de folder -test

**Pull request closed without merging**
