### PR TITLE
Prakiti smart patch 1

### PR DESCRIPTION
**Pull request by PrakitiSmart**
Added a fingerprint for "_TZ3000_zwaadvus/TS011F"

### CODE REVIEW

**Comment by Mariano-Github** [comment]
Hi [PrakitiSmart](https://github.com/PrakitiSmart)

Add a fingerprint for "_TZ3000_zwaadvus/TS011F", but what profile? 
the file is incomplete

**Comment by PrakitiSmart** [comment]
> 

I thoguht I did add two-outlet as device profile name.

**Comment by Mariano-Github** [comment]
Added a fingerprint for "_TZ3000_zwaadvus/TS011F" as two-outlet profile

**Comment by PrakitiSmart** [comment]
Added to main branch

**Pull request closed without merging**
